apiVersion: operators.coreos.com/v1alpha1
kind: ClusterServiceVersion
metadata:
  annotations:
    alm-examples: |-
      [
        {
          "apiVersion": "workspace.devfile.io/v1alpha1",
          "kind": "DevWorkspace",
          "metadata": {
            "annotations": {
              "controller.devfile.io/restricted-access": "true"
            },
            "labels": {
              "console.openshift.io/terminal": "true"
            },
            "name": "web-terminal"
          },
          "spec": {
            "routingClass": "web-terminal",
            "started": true,
            "template": {
              "components": [
                {
                  "plugin": {
                    "id": "redhat-developer/web-terminal/4.5.0",
                    "name": "web-terminal"
                  }
                }
              ]
            }
          }
        }
      ]
    capabilities: Basic Install
    categories: Developer Tools
    certified: "false"
    containerImage: quay.io/che-incubator/che-workspace-controller:nightly
    createdAt: "2020-05-27T05:12:57Z"
    description: Start a Web terminal in your browser with common CLI tools installed
      to work with cluster
    operators.operatorframework.io/internal-objects: '[]'
    repository: https://github.com/devfile/devworkspace-operator
    support: Red Hat, Inc.
  name: web-terminal.v2.0.0
  namespace: placeholder
spec:
  apiservicedefinitions: {}
  customresourcedefinitions:
    required:
    - description: Start a Web terminal in your browser with common CLI tools installed
        to work with cluster
      displayName: Workspace
      kind: DevWorkspace
      name: devworkspaces.workspace.devfile.io
      specDescriptors:
      - description: Expected status
        displayName: Started
        path: started
        x-descriptors:
        - urn:alm:descriptor:com.tectonic.ui:booleanSwitch
      statusDescriptors:
      - description: Workspace status
        displayName: Status
        path: phase
        x-descriptors:
        - urn:alm:descriptor:io.kubernetes.phase
      - description: Web Terminal ID
        displayName: ID of the Web Terminal
        path: workspaceId
        x-descriptors:
        - urn:alm:descriptor:text
      - description: Conditions of the workspace activity
        displayName: Conditions
        path: conditions
        x-descriptors:
        - urn:alm:descriptor:io.kubernetes.conditions
      version: v1alpha1
  description: Start a Web terminal in your browser with common CLI tools installed
    to work with cluster
  displayName: Web Terminal
  install:
    spec:
      clusterPermissions: []
      deployments: []
    strategy: deployment
  installModes:
  - supported: false
    type: OwnNamespace
  - supported: false
    type: SingleNamespace
  - supported: false
    type: MultiNamespace
  - supported: true
    type: AllNamespaces
  keywords:
  - workspaces
  - devtools
  - developer
  - ide
  - terminal
  links:
  - name: Web Terminal Repo
    url: https://github.com/redhat-developer/web-terminal-operator/
  maintainers:
  - email: dfestal@redhat.com
    name: David Festal
  - email: jpinkney@redhat.com
    name: Josh Pinkney
  maturity: alpha
  provider:
    name: Red Hat
  version: 2.0.0
